### ISSUE TITLE
Possible bug in set_roi

### ISSUE THREAD

**Issue by cmoriarty** [stevemarple/python-zwoasi#4]
I've been having trouble with set_roi function, and I think I found out why.  It looks like the code verifies the start_x/y positions incorrectly. 

Currently it divides the cam_info[MaxWidth] by 2, although should it by the "bins" variable?

        if start_x is None:
            start_x = (cam_info['MaxWidth'] - width) / 2
        if start_x + width > cam_info['MaxWidth'] / 2:
            raise ValueError('ROI and start position larger than binned sensor width')
        if start_y is None:
            start_y = (cam_info['MaxHeight'] - height) / 2
        if start_y + height > cam_info['MaxHeight'] / 2:
            raise ValueError('ROI and start position larger than binned sensor height')

I think the workaround is to just use bins=2, which will probably work fine for me now.  Just wanted to get your take on it.

**Comment by stevemarple** [comment]
Does it work OK without pixel binning? 

The idea was to centre the ROI if startx is not specified. IIRC the region of interest is considered after binning so I think cam_info['MaxWidth'] should be divided by the bin size to get the effective width. 

I'll try to test this tonight.

**Comment by cmoriarty** [comment]
As always - thanks for the fast reply. 

I do see the problem even without binning.  

The issue is in the 'if' statements ensuring the ROI is on the detector.  For my case, I am passing in values for start_x, start_y, height, width.  

example: 
start_x = 4455
start_y = 3319
width = 200
height = 200
bins = 1

The x,y end coordinates should be the upper right pixel on the detector (4655,3519), accounting for an index of 0. So these parameters should be legal.  

Alas, the code gets to line 381 and throws an error:

        if start_x + width > cam_info['MaxWidth'] / 2:
            raise ValueError('ROI and start position larger than binned sensor width')

I believe the issue is because of the divide by 2.  My initial thought was to change '2' to 'bins', but that also implies that you would need to divide start_x and width by bins.  Does it make sense to just remove the divide by 2?  As a test, I removed it, and everything seems to working now.  

Probably obvious, but the problem also applies to start_y.

**Comment by stevemarple** [comment]
I've pushed 0.0.16. That fixes the problem that valid ROI values could not be set.

The correct code is

**Comment by stevemarple** [comment]
I've pushed 0.0.16. The correct code is:
```
if start_x is None:
    start_x = ((cam_info['MaxWidth']/bins) - width) / 2
```
because `cam_info['MaxWidth']/bins` gives the effective width of the sensor after binning, the rest is to share out the unused pixels equally on either side of the ROI. I can use values of 1 or 2 for bins but after that I've had timeouts. I've not tried altering the USB bandwidth.

There's now another problem. The image is still correct after reducing the height but it is warped when the width is reduced. I can't see why right now and the SDK demo programs haven't given any clues so far.

**Comment by stevemarple** [comment]
I've pushed 0.0.17 and uploaded to Pypi. That contains an example for pixel binning. It works as expected on the ASI174MC but not the ASI178MC. I'm interested to hear how it works with the ASI1600MM, particularly when you use `set_roi()` to reduce the width and height.

**Comment by cmoriarty** [comment]
I updated my code with your fix and it works.  Thanks!
