### ISSUE TITLE
SetID not implemented

### ISSUE THREAD

**Issue by cmoriarty** [stevemarple/python-zwoasi#6]
It looks like SetID is in progress in the latest code:

```
# TO DO: need to confirm correct function call parameters
# def _set_id(id, id_str):
```

I have two of the same camera now, so I need to assign them IDs.  If helpful, here is the information I got from ZWO:

"You can write a 8bit long ID to camera by calling ASI_ERROR_CODE ASISetID(int iCameraID, ASI_ID ID), which is stored in the flash memory of camera, it won't lose when lost power, this ID will be attached to camera name, for example ID is "01" so the camera name ASI_CAMERA_INFO::Name will be "ASI290MC(01)"

I'm working on a solution in c++, but it would be great to have SetID in your python package.

**Comment by cmoriarty** [comment]
I was able to get some python code to work, although it's not pretty.

I added the following to __init__.py:

```
def _set_id(old_id, new_id):
    r = zwolib.ASISetID(old_id, new_id)
    if r:
        raise zwo_errors[r]
```

Under Camera class:
```
def set_id(self, old_id, new_id):
     return _set_id(old_id, new_id)
```

Then, if you pass the ascii representation of the ID you want, it will write it to its flash correctly.  The example below assumes you only have one camera connected.

Ex:
```
cam1.camera.set_id(0,49)
camera_info1 = cam1.camera.get_camera_property()
print(camera_info1)
>>> {'Name': 'ZWO ASI290MM(1)', ....

cam1.camera.set_id(0,50)
camera_info1 = cam1.camera.get_camera_property()
print(camera_info1)
>>> {'Name': 'ZWO ASI290MM(2)', ....

cam1.camera.set_id(0,0)
camera_info1 = cam1.camera.get_camera_property()
print(camera_info1)
>>> {'Name': 'ZWO ASI290MM', ....
```

**Comment by stevemarple** [comment]
Thanks, does the existing `cam1.get_id()` work as expected? Without `set_id()` I couldn't be certain it was correct.

**Comment by cmoriarty** [comment]
It didn’t work when I tried it.  It seemed to be returning a blank, although it didn’t raise an error.

**Comment by stevemarple** [comment]
I've not been able to the SDK function `GetID()` to work. I always get an `ASI_ERROR_GENERAL_ERROR` response back instead of `ASI_SUCCESS`. I'll raise a support request with ZWO. Without the ability to get the existing ID I can't make use of `SetID()`.
